# Generated by Django 4.2.1 on 2024-11-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblmovimientoanimales',
            name='IDCorral',
        ),
        migrations.RemoveField(
            model_name='tblmovimientoanimales',
            name='No_Guia',
        ),
        migrations.RemoveField(
            model_name='tblmovimientoanimales',
            name='Notas',
        ),
        migrations.AddField(
            model_name='tbldetallemovanimales',
            name='IDCorral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcorrales'),
        ),
        migrations.AddField(
            model_name='tbldetallemovanimales',
            name='No_Guia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tbldetallemovanimales',
            name='Notas',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tbldetalleanimales',
            name='No_Guia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tblmovimientoanimales',
            name='Fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tblmovimientoanimales',
            name='NoPartida',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
