# Generated by Django 4.2.1 on 2024-11-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldetalleanimales',
            name='No_Guia',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
