# Generated by Django 4.2.1 on 2024-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRepMovAnCl',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRepMovAnCo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRepMovAnim',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRepMovEntM',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRepMovSalM',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
