# Generated by Django 4.2.1 on 2024-07-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_tblservido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblservido',
            name='FechaAServir',
            field=models.DateTimeField(max_length=150, null=True),
        ),
    ]
