# Generated by Django 4.2.1 on 2024-07-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_tblconfiguracion_foliorepmovancl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblservido',
            name='FechaAServir',
            field=models.DateField(max_length=150, null=True),
        ),
    ]
