# Generated by Django 4.2.1 on 2024-11-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_tblasignacorrales_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRePorMovAn',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
