# Generated by Django 4.2.1 on 2024-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_tblservido_fechaaservir'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldetallemovanimales',
            name='PesoPromedio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbldetallemovanimales',
            name='PesoTotal',
            field=models.IntegerField(null=True),
        ),
    ]
