# Generated by Django 4.2.1 on 2024-07-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_tblservido_fechaaservir'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRepServLiq',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRepServMov',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
