# Generated by Django 4.2.1 on 2024-07-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_tbleventosvalmosys'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioSalMaquila',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
