# Generated by Django 4.2.1 on 2024-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_tblconfiguracion_foliorepormovan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmovimientoanimales',
            name='Notas',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
