# Generated by Django 4.2.1 on 2024-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_tbldetallemovanimales_pesopromedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldetallemovanimales',
            name='PesoPromedio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tbldetallemovanimales',
            name='PesoTotal',
            field=models.FloatField(null=True),
        ),
    ]
