# Generated by Django 4.2.1 on 2024-07-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_tblconfiguracion_foliosalmaquila'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioEntMatPrima',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioEntProducto',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioSalMatPrima',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioSalProducto',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
